### PR TITLE
TypeScript support

### PR DESCRIPTION
**Pull request by onokumus**

### CODE REVIEW

**Comment by jonschlinkert** [comment]
Thanks! sorry I missed these prs! I'm wrapping up a project, I'll try to get these merged in the next day or two (or maybe @doowb can if he has time).

**Comment by jonschlinkert** [comment]
btw, I'm about to publish a new version of [gray-matter](https://github.com/jonschlinkert/gray-matter), any interest in helping to update the typings in that project after I push it up? I'm not familiar with typescript unfortunately

**Comment by onokumus** [comment]
I would like to gladly help with typescript.

**Comment by tunnckoCore** [comment]
It's a lot better to submit directly to @DefinitelyTyped or [flowtype/flow-typed](https://github.com/flowtype/flow-typed), instead of adding to every single project. :)

**Comment by doowb** [comment]
@onokumus thanks for the PR. I'll get this published soon.

@tunnckoCore thanks for the information. I don't think anyone would object to having these projects submitted to those services (it still looks like you have to do a PR and manually creating the typescript files for each project though).

**Comment by jonschlinkert** [comment]
> It's a lot better to submit directly to @DefinitelyTyped or flowtype/flow-typed, instead of adding to every single project. :)

Yeah like having a github project that lists all of the versions of all npm packages, so you could install that every time you need a single package. sounds like a fantastic idea

**Comment by tunnckoCore** [comment]
@jonschlinkert haha.. don't mess wit me, i'm the god! :laughing: jk. Anyway, just forget about that before one month or so. I will never be against you, don't get it so hard. I just don't have time to explain and discuss WHATs and WHYs around this "duplication" of Base, they exists for few reasons and they follow your concept for plugin architecture, which is nothing more than good thing. Anyway.

As about the main topic, yea i'm agree. And i still can't consider on which side I am, but both make sense to me. Probably your more right, cuz it is centralized. When the lib is updated types get updated too, instead of going somewhere else and PR for updates there. Hm.

**Pull request merged**
