### PR TITLE
Remove bower support

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by jonschlinkert** [comment]
@TrySound I'm really sorry for taking so long to get back to you. I invited you to be a collaborator so you can merge in your changes. I'll also add you to NPM. thanks for the PRs!

**Comment by TrySound** [comment]
thank you!

**Comment by TrySound** [comment]
@jonschlinkert could you give me an access to this project too?
https://github.com/jonschlinkert/is-plain-object

**Comment by jonschlinkert** [comment]
Yes, I just stepped away from my computer, I’ll do it when I get back online later. Don’t hesitate to ping me later tonight or tomorrow if I forget

**Pull request merged**
